info: ✅ Server started at http://localhost:3000/api/ {"timestamp":"2025-06-14T05:41:28.689Z"}
error: Could not connect to the database. getaddrinfo EAI_AGAIN dhronacharya.c3m8ecio4z3m.ap-south-1.rds.amazonaws.com {"name":"SequelizeConnectionError","original":{"code":"EAI_AGAIN","errno":-3001,"hostname":"dhronacharya.c3m8ecio4z3m.ap-south-1.rds.amazonaws.com","syscall":"getaddrinfo"},"parent":{"code":"EAI_AGAIN","errno":-3001,"hostname":"dhronacharya.c3m8ecio4z3m.ap-south-1.rds.amazonaws.com","syscall":"getaddrinfo"},"stack":"SequelizeConnectionError: getaddrinfo EAI_AGAIN dhronacharya.c3m8ecio4z3m.ap-south-1.rds.amazonaws.com\n    at Client._connectionCallback (E:\\Drona-project\\dhronacharya-backend\\node_modules\\sequelize\\lib\\dialects\\postgres\\connection-manager.js:145:24)\n    at Client._handleErrorWhileConnecting (E:\\Drona-project\\dhronacharya-backend\\node_modules\\pg\\lib\\client.js:336:19)\n    at Client._handleErrorEvent (E:\\Drona-project\\dhronacharya-backend\\node_modules\\pg\\lib\\client.js:346:19)\n    at Connection.emit (node:events:519:28)\n    at Connection.emit (node:domain:488:12)\n    at Socket.reportStreamError (E:\\Drona-project\\dhronacharya-backend\\node_modules\\pg\\lib\\connection.js:57:12)\n    at Socket.emit (node:events:519:28)\n    at Socket.emit (node:domain:488:12)\n    at emitErrorNT (node:internal/streams/destroy:169:8)\n    at emitErrorCloseNT (node:internal/streams/destroy:128:3)\n    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)","timestamp":"2025-06-14T05:41:28.702Z"}
info: ✅ Server started at http://localhost:3000/api/ {"timestamp":"2025-06-14T05:47:03.381Z"}
error: Could not connect to the database. connect ETIMEDOUT 3.7.92.217:5432 {"name":"SequelizeConnectionError","original":{"address":"3.7.92.217","code":"ETIMEDOUT","errno":-4039,"port":5432,"syscall":"connect"},"parent":{"address":"3.7.92.217","code":"ETIMEDOUT","errno":-4039,"port":5432,"syscall":"connect"},"stack":"SequelizeConnectionError: connect ETIMEDOUT 3.7.92.217:5432\n    at Client._connectionCallback (E:\\Drona-project\\dhronacharya-backend\\node_modules\\sequelize\\lib\\dialects\\postgres\\connection-manager.js:145:24)\n    at Client._handleErrorWhileConnecting (E:\\Drona-project\\dhronacharya-backend\\node_modules\\pg\\lib\\client.js:336:19)\n    at Client._handleErrorEvent (E:\\Drona-project\\dhronacharya-backend\\node_modules\\pg\\lib\\client.js:346:19)\n    at Connection.emit (node:events:519:28)\n    at Connection.emit (node:domain:488:12)\n    at Socket.reportStreamError (E:\\Drona-project\\dhronacharya-backend\\node_modules\\pg\\lib\\connection.js:57:12)\n    at Socket.emit (node:events:519:28)\n    at Socket.emit (node:domain:488:12)\n    at emitErrorNT (node:internal/streams/destroy:169:8)\n    at emitErrorCloseNT (node:internal/streams/destroy:128:3)\n    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)","timestamp":"2025-06-14T05:47:24.473Z"}
